{% set name = "robotraconteur" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/robotraconteur/robotraconteur.git
  git_rev: v{{ version }}

build:
  number: 1

requirements:
  host:
    - git
    - cmake
    - boost-cpp
    - python
    - swig
    - numpy
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
    - pip
    - dbus  # [linux]
    - zlib  # [linux]
    - openssl  # [linux]
    - libusb  # [linux]
    - libbluetooth-headers  # [linux]
  run:
    - boost-cpp
    - python
    - numpy

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteur.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteur.h (exit 0) else (exit 1)  # [win]

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Communication framework for robotics and automation'

extra:
  recipe-maintainers:
    - johnwason
