package:
  name: robotraconteur
  version: 0.17.0

source:
  git_url: https://github.com/robotraconteur/robotraconteur.git
  git_rev: v0.17.0

requirements:
  host:
    - git
    - cmake
    - boost-cpp
    - python
    - swig
    - numpy
    - ninja # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make # [linux]
    - pip
    - dbus # [linux]
    - zlib # [linux]
    - openssl # [linux]
    - libusb # [linux]
    - libbluetooth-headers # [linux]
  run:
    - boost-cpp
    - python
    - numpy

build:
  number: 0

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Communication framework for robotics and automation'

