{% set name = "robotraconteur" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotraconteur/robotraconteur/archive/refs/tags/v1.0.0.tar.gz
    sha256: '94c6ca93f2bdfaa9dc41bb439e9da97b395c520d56fb4f19451c12e9ef7b3bbe'
  - url: http://www.kernel.org/pub/linux/bluetooth/bluez-5.56.tar.xz  # [linux]
    sha256: 59c4dba9fc8aae2a6a5f8f12f19bc1b0c2dc27355c7ca3123eed3fe6bd7d0b9d  # [linux]
    folder: bluez-src  # [linux]

build:
  number: 0
  run_exports:
  - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]    
    - make  # [linux]
    - git
    - cmake
    - swig
  host:    
    - libboost-devel
    - python
    - pip
    - numpy
    - dbus  # [linux]
    - zlib  # [linux]
    - openssl  # [linux]
    - libusb  # [linux]
  run:
    - python
    - numpy

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteur.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteur.h (exit 0) else (exit 1)  # [win]
    - test -f ${PREFIX}/lib/libRobotRaconteurCore.a  # [linux]
    - test -f ${PREFIX}/lib/libRobotRaconteurCore.a  # [osx]
    - if exist %PREFIX%\\Library\\lib\\libRobotRaconteurCore.lib (exit 0) else (exit 1)  # [win]
    - python -c "from RobotRaconteur.Client import RRN; print(RRN.RobotRaconteurVersion)"

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Communication framework for robotics and automation'

extra:
  recipe-maintainers:
    - johnwason
