package:
  name: robotraconteur
  version: 0.15.2.3

source:
  git_url: https://github.com/robotraconteur/robotraconteur.git
  git_depth: 10
  git_rev: v0.15.2
  patches:
    - fix_osx_python.patch # [osx]
    - fix_osx_net.patch # [osx]

requirements:
  host:
    - git
    - cmake
    - boost-cpp
    - python
    - swig
    - numpy
    - ninja # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make # [linux]
    - pip
    - dbus # [linux]
    - zlib # [linux]
    - openssl # [linux]
    - libusb # [linux]
    - libbluetooth-headers # [linux]
  run:
    - boost-cpp
    - python
    - numpy

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Communication framework for robotics and automation'

