github:
  user_or_org: robotraconteur

channels:
  targets:
    - ["robotraconteur", "main"]

provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
  linux_aarch64: github_actions
  linux_ppc64le: None

github_actions:
  upload_packages: True
  store_build_artifacts: True